# Generated by Django 4.0.4 on 2022-06-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('SKU', models.CharField(max_length=30, unique=True)),
                ('available', models.BooleanField(default=True)),
                ('imagen', models.ImageField(null=True, upload_to='productos_imagenes')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
            },
        ),
    ]
