# Generated by Django 4.0.4 on 2022-06-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_productos_herramientas_clase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
