# Generated by Django 4.0.4 on 2022-05-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0003_alter_familiares_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiares',
            name='fecha_nacimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
