# Generated by Django 4.0.4 on 2022-05-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0004_familiares_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiares',
            name='dni',
            field=models.IntegerField(max_length=8),
        ),
        migrations.AlterField(
            model_name='familiares',
            name='edad',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
