# Generated by Django 4.0.4 on 2022-05-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0005_alter_familiares_dni_alter_familiares_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiares',
            name='dni',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='familiares',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='familiares',
            name='fecha_nacimiento',
            field=models.CharField(max_length=100),
        ),
    ]
